# _config.yml
# ソースディレクトリと出力ディレクトリの設定
# source: 
# destination: _site

# Markdownとシンタックスハイライターの設定
markdown: GFM
plugins:
 - jekyll-sitemap
highlighter: rouge

# シンタックスハイライトの設定
rouge:
  enabled: true
  guess_lang: false
  default_lang: rust