# _config.yml
# ソースディレクトリと出力ディレクトリの設定
# source: 
# destination: _site

# Markdownとシンタックスハイライターの設定
markdown: kramdown
plugins:
 - jekyll-sitemap
highlighter: rouge

# kramdownの設定
kramdown:
  hard_wrap: true
  input: GFM
  syntax_highlighter: rouge

# シンタックスハイライトの設定
rouge:
  enabled: true
  guess_lang: false
  default_lang: rust
