# Markdownとシンタックスハイライターの設定
markdown: GFM # 表形式に対応
plugins:
 - jekyll-sitemap
highlighter: rouge

# シンタックスハイライトの設定
rouge:
  enabled: true
  guess_lang: false
  default_lang: rust
  theme: monokai.sublime