# _config.yml
# ソースディレクトリと出力ディレクトリの設定
source: docs
destination: _site

# Markdownとシンタックスハイライターの設定
markdown: kramdown
plugins:
 - jekyll-sitemap
highlighter: rouge

# kramdownの設定
kramdown:
  hard_wrap: true

